# Generated by Django 4.1.1 on 2022-11-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=20)),
                ('hobby', models.CharField(choices=[('Reading', 'R'), ('Listening to music', 'L'), ('Play Sport', 'PS')], max_length=20)),
            ],
        ),
    ]
